version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_INITDB_SCRIPT: "./sql/schema.sql"
    volumes:
      - ./Orchestrator/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports: 
      - "${POSTGRES_PORT}:5432"
