version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_INITDB_SCRIPT: "./sql/schema.sql"
    volumes:
      - ./Orchestrator/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports: 
      - "${POSTGRES_PORT}:5432"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "habrpguser@habr.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4habr"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  orchestrator:
    container_name: "orch_container"
    build:
      context: ""
      dockerfile: Orchestrator/Dockerfile
    environment:
      DB_NAME: "${DB_NAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_HOST: "${POSTGRES_HOST}"

    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - "postgres" 

  agent:
    container_name: "agent_container"
    build: 
      context: ""
      dockerfile: Agent/Dockerfile
    environment:
      orchURL : "${orchURL}"
      MAX_GOROUTINE: "${MAX_GOROUTINE}"
    restart: always
    depends_on:
      - "orchestrator"
volumes:
  pgadmin-data:
